dailyfresh_13/apps/cart/urls.py
from django.conf.urls import url
from cart import views

urlpatterns = [
    url(r"^add$", views.AddCartView.as_view(), name="add"),
    url(r"^$", views.CartInfoView.as_view(), name="info"),
    url(r"^update$", views.UpdateCartView.as_view(), name="update"),
    url(r"^delete$", views.DeleteCartView.as_view(), name="delete"),
]

dailyfresh_13/apps/goods/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r"^index$", views.IndexView.as_view(), name="index"),
    url(r"^detail/(?P<sku_id>\d+)$", views.DetailView.as_view(), name="detail"),
    url(r"^list/(?P<category_id>\d+)/(?P<page>\d+)$", views.ListView.as_view(), name="list"),

]

dailyfresh_13/apps/orders/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r"^place$", views.PlaceOrderView.as_view(), name="place"),
    url(r"^commit$", views.CommitOrderView.as_view(), name="commit"),
    url('^(?P<page>\d+)$', views.UserOrdersView.as_view(), name="info"),
    url('^pay$', views.PayView.as_view(), name="pay"),
    url('^check_pay$', views.CheckPayStatusView.as_view(), name="check_pay"),
]

dailyfresh_13/apps/users/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^register$', views.RegisterView.as_view(), name="register"),
    # 激活的请求
    url(r'^active/(?P<token>.+)', views.ActiveView.as_view(), name="active"),
    # 登陆的请求路径
    url(r'^login$', views.LoginView.as_view(), name="login"),
    # 定义退出的请求路径
    url(r'^logout$', views.LogoutView.as_view(), name="logout"),
    # 定义用户通过登陆后的地址信息
    url(r'^address$', views.AddressView.as_view(), name="address"),

    url(r'^info$', views.UserInfoView.as_view(), name="info"),

]

dailyfresh_13/dailyfresh_13/urls.py
from django.conf.urls import include, url
from django.contrib import admin

import users.urls
import goods.urls
import tinymce.urls
import haystack.urls
import cart.urls
import orders.urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    # 富文本编辑器
    url(r'^tinymce/', include(tinymce.urls)),
    url(r'^search/', include(haystack.urls)),
    url(r'^users/', include(users.urls, namespace='users')),
    url(r'^cart/', include(cart.urls, namespace="cart")),
    url(r'^', include(goods.urls, namespace="goods")),
    url(r'^orders/', include(orders.urls, namespace="orders")),
]

dailyfresh_13/apps/cart/models.py
from django.db import models

# Create your models here.

dailyfresh_13/apps/cart/views.py
from django.shortcuts import render
from django.views.generic import View
from django.http import JsonResponse
from goods.models import GoodsSKU
from django_redis import get_redis_connection
import json


class AddCartView(View):
    """添加购物车"""
    def post(self, request):
        # 判断用户是否登录
        # if not request.user.is_authenticated():
        #     # 表示用户未登录
        #     return JsonResponse({"code": 1, "message": "用户未登录"})

        # sku_id 商品id
        # count 商品数量
        # 接受参数
        sku_id = request.POST.get("sku_id")
        count = request.POST.get("count")

        # 校验参数
        if not all([sku_id, count]):
            return JsonResponse({"code": 2, "message": "参数不完整"})

        # 判断商品存在与否
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            # 表示商品不存在
            return JsonResponse({"code": 3, "message": "商品不存在"})

        # 判断用户请求的count是不是整数
        try:
            count = int(count)
        except Exception:
            # 数量不是整数
            return JsonResponse({"code": 4, "message": "参数错误"})

        # 判断数量有没有超过库存
        if count > sku.stock:
            return JsonResponse({"code": 5, "message": "库存不足"})
        if request.user.is_authenticated():
            # 业务逻辑处理，将数据保存到redis中
            # {"sku_1": 10, "sku_2": 20}
            redis_conn = get_redis_connection("default")

            # 先从redis中尝试获取用户原有购物车中相同商品的信息
            user_id = request.user.id
            origin_count = redis_conn.hget("cart_%s" % user_id, sku_id)

            # 如果redis中不存在，则直接将数据保存到redis的购物车中
            # 如果redis中原本包含了这个商品的数量信息， 进行数量累加，在保存到redis中
            if origin_count is not None:
                count += int(origin_count)
            # 在把新的购物信息设置会 redis中
            redis_conn.hset("cart_%s" % user_id, sku_id, count)
            cart_num = 0
            # 取出所有的购物车的数量返回给前端
            cart =redis_conn.hgetall('cart_%s' %user_id)
            for val in cart.values():
                cart_num +=int(val)
            # 通过返回json数据，告知前端处理的结果
            return JsonResponse({"code": 0, "message": "添加购物车成功",'cart_num':cart_num})
        else:
            # 如果用户未登录，则将数据保存到cookie中
            # 先获取用户的cookie中的购物车数据
            cart_json = request.COOKIES.get("cart") # 取原来存储在浏览器中的cookie
            if cart_json is not None:
                cart=json.loads(cart_json)    # 把原来的转成字典
            else:
                cart={}
            # 判断cookies是否包含传来的商品shu_id如果有则求和，没有则增加
            if sku_id in cart:   # 判断传过来的商品id是在以前的cookies中有，有则叠加
                origin_count= cart[sku_id]
                count += origin_count

            # 把最新的商品数量设置到字典中
            cart[sku_id]=count
            new_cart_json = json.dumps(cart)

            # 统计购物车中的商品总数
            cart_num = 0
            for val in cart.values():
                cart_num += val

            response = JsonResponse({"code": 0, "message": "添加购物车成功", "cart_num": cart_num})
            # 设置最新的cookie信息

            response.set_cookie('cart',new_cart_json)
            return response

class CartInfoView(View):
    def get(self, request):

        # 1 用户登陆的时候,从redis中获取数据
        # 2 用户未登录的时候,从cookie中获取数据
        if request.user.is_authenticated():
            user_id=request.user.id
            redis_con = get_redis_connection('default')
            cart = redis_con.hgetall('cart_%s' % user_id)
        else:
            cart_json = request.COOKIES.get('cart')
            if cart_json is not None:
                print(cart_json,type(cart_json))
                cart = json.loads(cart_json)
            else:
                cart={}
        # 遍历cart字典购物车，从mysql数据中查询商品信息
        print(cart,type(cart))
        skus = []
        total_count = 0  # 商品总数
        total_amount = 0  # 商品总金额
        for sku_id,count in cart.items():
            try:
                sku = GoodsSKU.objects.get(id=sku_id)
            except GoodsSKU.DoesNotExist:
                continue
            count = int(count)
            sku.count=count
            skus.append(sku)
            amount = sku.price * count  # price字段是DecimalField, 在python中是Decimal数据类型
            sku.amount = amount
            total_amount +=amount
            total_count +=count

        context = {
            "skus": skus,
            "total_count": total_count,
            "total_amount": total_amount
        }

        return render(request, 'cart.html', context)


class UpdateCartView(View):

    def post(self,request):
        # 接受前端传送过来的数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')
        # 参数校验
        if not all([sku_id, count]):
            return JsonResponse({'code':1, 'message': '参数不完整'})
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'code':2, 'message' :'商品不存在'})
        try:
            count = int(count)
        except Exception:
            return JsonResponse({'code':3, 'message': '参数有误'})

        if count > sku.stock:
            return JsonResponse({'code':4, 'message': '库存不足'})
        # 业务处理保存数据
        if not request.user.is_authenticated():
            # 如果用户未登录，把数据保存在cookie中
            cart_json = request.COOKIES.get('cart')
            if cart_json is not None:
                cart = json.loads(cart_json)
            else:
                cart=[]
            # 把最新的数量信息保存
            cart[sku_id]=count
            response = JsonResponse({'code':0,'message': '修改成功'})
            response.set_cookie('cart',json.dumps(cart))
            return response

        else:
            # 如果用户登陆，把数据保存在redis中
            redis_con= get_redis_connection('default')
            user_id = request.user.id
            # 把数据设置到redis中
            redis_con.hset("cart_%s" % user_id, sku_id, count)
            # 返回结果， 返回Json数据
            return JsonResponse({"code": 0, "message": "修改成功"})



class DeleteCartView(View):
    def post(self, request):
        # 接受参数
        sku_id = request.POST.get('sku_id')
        # 参数校验
        if not sku_id:
            return JsonResponse({'code':1,'message':'参数不完整'})

        # 根据sku_id把对应的商品删除
        if not request.user.is_authenticated():
            # 如果用户未登录，从cookie中删除数据
            cart_json = request.COOKIES.get('cart')
            if cart_json is not None:
                cart = json.loads(cart_json)
                if sku_id in cart:
                    del cart[sku_id]

                response = JsonResponse({'code':0, 'message':'删除成功'})
                response.set_cookie('cart',json.dumps(cart))
                return response
            else:
                return JsonResponse({'code':0 ,'message': '删除成功'})

        else:
            # 如果用户登陆，从redis中删除数据
            redis_con = get_redis_connection('default')
            user_id = request.user.id
            redis_con.hdel('cart_%s' % user_id, sku_id)
            return JsonResponse({'code':0,'message': '删除成功'})

dailyfresh_13/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {% block topfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
    {% endblock %}
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
                {% if user.is_authenticated %}
				<div class="login_btn fl">
                    欢迎您：<em>{{ user.username }}</em>
					<span>|</span>
					<a href="{% url 'users:logout' %}">退出</a>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'users:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'users:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'users:info' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:info' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'orders:info' 1 %}">我的订单</a>
				</div>
			</div>
		</div>		
	</div>
    {% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url "goods:index" %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
            <form action="/search/" method="get">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:info' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_num }}</div>
		</div>
	</div>
    {% endblock %}

    {% block body %}{% endblock %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
    {% block footer %}{% endblock %}
    {% block bottom_files %}{% endblock %}
</body>
</html>

dailyfresh_13/templates/list.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}天天生鲜-商品列表{% endblock %}

{% block body %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
                    {% for category in categorys %}
					<li><a href="{% url 'goods:list' category.id 1 %}" class="{{ category.logo }}">{{ category.name }}</a></li>
                    {% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="{% url 'goods:index' %}">全部分类</a>
		<span>></span>
		<a href="{% url 'goods:list' category.id 1 %}">新鲜水果</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for sku in new_skus %}
					<li>
						<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.default_image.url }}"></a>
						<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
						<div class="prize">￥{{ sku.price }}</div>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="{% url 'goods:list' category.id 1 %}?sort=default" {% if sort == "default" %}class="active"{% endif %}>默认</a>
				<a href="{% url 'goods:list' category.id 1 %}?sort=price" {% if sort == "price" %}class="active"{% endif %}>价格</a>
				<a href="{% url 'goods:list' category.id 1 %}?sort=hot" {% if sort == "hot" %}class="active"{% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">
                {% for sku in page_skus %}
				<li>
					<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.default_image.url }}"></a>
					<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ sku.price }}</span>
						<span class="unit">{{ sku.price }}/{{ sku.unit }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {%  endfor %}
			</ul>

			<div class="pagenation">
                {%  if page_skus.has_previous %}
				<a href="{{ page_skus.previous_page_number }}">上一页</a>
                {% endif %}
                {%  for p in  page_list %}
				<a href="{% url 'goods:list' category.id p %}?sort={{ sort }}" {% if p == page_skus.number %}class="active"{% endif %}>{{ p }}</a>
                {%  endfor %}
                {%  if page_skus.has_next %}
				<a href="{{ page_skus.next_page_number }}">下一页></a>
                {% endif %}
			</div>
		</div>
	</div>
{% endblock %}

dailyfresh_13/templates/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-登录</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>
	<div class="login_top clearfix">
		<a href="{% url 'goods:index' %}" class="login_logo"><img src="{% static 'images/logo02.png' %}"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'users:register' %}">立即注册</a>
				</div>
				<div class="form_input">
					<form method="post">
                        {% csrf_token %}
						<input type="text" name="username" class="name_input" placeholder="请输入用户名">
{#						<div class="user_error">输入错误</div>#}
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
{#						<div class="pwd_error">输入错误</div>#}
                        <div class="pwd_error">{{ errmsg }}</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="remembered">
							<label>记住用户名</label>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

</body>
</html>

dailyfresh_13/templates/static_base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {% block topfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
    {% endblock %}
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_btn fl">
					<a href="{% url 'users:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'users:register' %}">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="#">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="user_center_order.html">我的订单</a>
				</div>
			</div>
		</div>		
	</div>
    {% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url "goods:index" %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
            <form action="/search/" method="get">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
		<div class="guest_cart fr">
			<a href="#" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_num }}</div>
		</div>
	</div>
    {% endblock %}

    {% block body %}{% endblock %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
    {% block footer %}{% endblock %}
    {% block bottom_files %}{% endblock %}
</body>
</html>

dailyfresh_13/templates/user_center_base.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}天天生鲜-用户中心{% endblock %}

{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
            <form method="get" action="/search/">
			<input type="text" class="input_text fl" name="q" placeholder="搜索商品">
			<input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
	</div>
{% endblock %}

dailyfresh_13/templates/user_center_info.html
{% extends "user_center_base.html" %}
{% load staticfiles %}

{% block body %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'users:info' %}" class="active">· 个人信息</a></li>
				<li><a href="{% url 'orders:info' 1 %}">· 全部订单</a></li>
				<li><a href="{% url 'users:address' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ user.username }}</li>
							<li><span>联系方式：</span>{{ address.receiver_mobile }}</li>
							<li><span>联系地址：</span>{{ address.detail_addr }}</li>
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
                        {% for sku in skus %}
				<li>
					<a href="detail.html"><img src="{{ sku.default_image.url }}"></a>
					<h4><a href="detail.html">{{ sku.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ sku.price }}</span>
						<span class="unit">{{ sku.price }}/{{ sku.unit }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                        {% endfor %}

			</ul>
		</div>
		</div>
	</div>
{% endblock %}

dailyfresh_13/templates/user_center_order.html
{% extends 'user_center_base.html' %}

{% load staticfiles %}

{% block title %}天天生鲜-用户中心{% endblock %}

{% block body %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'users:info' %}">· 个人信息</a></li>
				<li><a href="{% url 'orders:info' 1 %}" class="active">· 全部订单</a></li>
				<li><a href="{% url 'users:address' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
				{% for order in orders %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{order.create_time}}</li>
					<li class="col02">订单号：{{order.order_id}}</li>
					<li class="col02 stress">{{order.status_name}}</li>
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
								{% for sku in order.skus %}
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="{{sku.default_image.url}}"></li>
									<li class="col02">{{sku.name}}<em>{{sku.price}}/{{sku.unit}}</em></li>
									<li class="col03">{{sku.count}}</li>
									<li class="col04">{{sku.amount}}元</li>
								</ul>
								{% endfor %}
							</td>
							<td width="15%">{{order.total_amount}}元<br/>（含运费{{order.trans_cost}}元）</td>
							<td width="15%">{{order.pay_method_name}}</td>
							<td width="15%"><a href="javascript:;" order_id="{{order.order_id}}" order_status="{{order.status}}" class="oper_btn">
                                {{ order.status_name }}
							</a></td>
						</tr>
					</tbody>
				</table>
				{% endfor %}

				<div class="pagenation">
				{% if orders.has_previous %}
					<a href="{% url 'orders:info' orders.previous_page_number %}"><上一页</a>
				{% endif %}
				{% for p in pages %}
					<a href="{% url 'orders:info' p %}" {% if p == order.number %}class="active"{% endif %}>{{p}}</a>
				{% endfor %}
				{% if orders.has_next %}
					<a href="{% url 'orders:info' orders.next_page_number %}">下一页></a>
				{% endif %}
				</div>
		</div>
	</div>
{% endblock %}

{% block bottom_files %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript">
		$('.oper_btn').click(function() {
			var order_id = $(this).attr("order_id");
			var order_status = $(this).attr("order_status");
			order_status = parseInt(order_status);
			if (1 == order_status) {
			    // 表示待支付
                var req_data ={
                    order_id:order_id,
                    csrfmiddlewaretoken: "{{ csrf_token }}"
                }
				$.post('/orders/pay', req_data, function(data){
                    if ( 1 == data.code ) {
                        // 用户未登录
                        location.href = "/users/login";
                    } else if (0 == data.code ) {
                        // 发起支付请求成功
                        window.open(data.url);
                        // 向后端发起查询支付状态的请求
                        $.get("/orders/check_pay?order_id="+order_id, function (resp_data) {
                            if (0 == resp_data) {
                                // 支付成功
                                location.reload();
                            } else {
                                alert(resp_data.message);
                            }
                        });
                    } else {
                        alert(data.message);
                    }
				});
			} else if (4 == order_status) {
				location.href = ("/orders/comment/" + order_id);
			} 
		});
	</script>
{% endblock %}